[workspace]
members = ["rust_src/remacs-lib", "etc/colors", "rust_src/crates/*"]
exclude = ["rust_src/ng-bindgen"]

[workspace.dependencies]
libc = "0.2"
log = "0.4"
errno = "0.3"
gtk = "0.18"
gdk = "0.18"
gtk-sys = "0.18"
gdk-sys = "0.18"
gdkwayland-sys = "0.18"
gdkx11-sys = "0.18"
parking_lot = "0.12"
fxhash = "0.2"
raw-window-handle = "0.6"
image = "0.24"
cfg_aliases = "0.2"
gleam = "0.15"
winit = { version = "0.29", default-features = false, features = ["rwh_06"]}
arboard = "3.3"
euclid = "0.22"
lazy_static = "1.4"
tokio = "1"
regex = "1.10"

[workspace.dependencies.webrender]
git = "https://github.com/declantsien/webrender.git"
rev = "6766059a74135ee6ff26fd4f0f1f25db5c8e772e"
default-features = false

[workspace.dependencies.webrender_api]
git = "https://github.com/declantsien/webrender.git"
rev = "6766059a74135ee6ff26fd4f0f1f25db5c8e772e"
default-features = false

# Allow unwinding in functions called from C. See
# https://www.reddit.com/r/rust/comments/565q1f/wrote_a_blogpost_from_my_experiences_the_arduous/d8h053m/
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
# This reduces the binary size from 125M to 70M due
# to Deno inclusion
opt-level = 'z' # Optimize for size

### Root package
[package]
authors = ["emacs-ng members"]
name = "emacsng"
description = "Experimental emacs fork"
license = "GPL-3.0"
version = "0.1.0"
edition = "2018"
build = "rust_src/build.rs"

[dependencies]
libc = "0.2"
remacs-lib = { version = "0.1.0", path = "rust_src/remacs-lib" }
emacs = { version = "0.1.0", path = "rust_src/crates/emacs" }
lisp-util = { version = "0.1.0", path = "rust_src/crates/lisp_util" }
lisp-macros = { version = "0.1.0", path = "rust_src/crates/lisp_macros" }
ng_async = { version = "0.1.0", path = "rust_src/crates/ng_async" }
lsp_json = { version = "0.1.0", path = "rust_src/crates/lsp_json" }
git = { version = "0.1.0", path = "rust_src/crates/git", optional = true }
font = { version = "0.1.0", path = "rust_src/crates/font", optional = true }
ng_module = { version = "0.1.0", path = "rust_src/crates/ng_module", optional = true }
js = { version = "0.1.0", path = "rust_src/crates/js", optional = true }
winit-term = { version = "0.1.0", path = "rust_src/crates/winit-term", optional = true }
clippy = { version = "*", optional = true }
log.workspace = true
tracing = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
features = [
  "matchers",
  "regex",
  "once_cell",
  "tracing",
  "std",
  "thread_local",
  "env-filter"
]

[dependencies.gl-renderer]
version = "0.1.0"
path = "rust_src/crates/gl-renderer"
default-features = false
optional = true

[build-dependencies]
ng-bindgen = { path = "rust_src/ng-bindgen" }

[lib]
crate-type = ["staticlib"]
path = "rust_src/lib.rs"

[features]
default = []

# Compile with C xml2 library support.
use-xml2 = []
window-system-x = ["emacs/window-system-x"]
window-system-ns = ["emacs/window-system-ns"]
window-system-w32=["emacs/window-system-w32"]
window-system-haiku=["emacs/window-system-haiku"]
window-system-pgtk=["emacs/window-system-pgtk"]
window-system-android=["emacs/window-system-android"]
window-system-winit = ["emacs/window-system-winit",
"dep:winit-term",
  "ng-bindgen/window-system-winit",
  "webrender",]
# Build with git2rs support
libgit = ["git", "ng-bindgen/libgit"]
# Use the webrender
webrender = [
  "dep:font",
  "emacs/webrender",
  "ng-bindgen/gl-renderer",
  "dep:gl-renderer",
]
# Treat warnings as a build error on Travis.
strict = []
# Use JavaScript and Deno
javascript = ["dep:js", "ng-bindgen/javascript"]
# Build with dynamic modules support's extensions.
ng-module = ["dep:ng_module", "ng-bindgen/ng-module"]
# Enable glyphs debugging code.
glyph-debug = ["gl-renderer?/capture"]
profiling = ["gl-renderer?/profiling"]

### Patches

# fontconfig font dirs patch
[patch.crates-io.font-loader]
git = "https://github.com/declantsien/rust-font-loader.git"
rev = "9e1776052d906f6cd3b78aa701ffb2d657877830"

# surfman raw-window-handle 0.6
[patch.crates-io.surfman]
git = "https://github.com/declantsien/surfman.git"
rev = "51ac8db9f4584bcad9d8223103386bd05c5f2048"

# glutin raw-window-handle 0.6
[patch.crates-io.glutin]
git = "https://github.com/declantsien/glutin.git"
rev = "92a5ab0cc907ab3e1095ec6a09356aff8d93ade8"

# unreleased webp has_animation patch
[patch.crates-io.image]
git = "https://github.com/image-rs/image.git"
rev = "5d031ed19b83d876190123cc6fc8b8b203b32814"
